### ISSUE TITLE
AttributeError: 'BiSeNet' object has no attribute 'module'

### ISSUE THREAD

**Issue by Eileen2014** [ooooverflow/BiSeNet#1]
load model from ./checkpoints/epoch_295.pth ...
Traceback (most recent call last):
  File "c:\Users\Administrator\Desktop\BiSeNet-master\BiSeNet-master\demo.py", line 80, in <module>
    main(params)
  File "c:\Users\Administrator\Desktop\BiSeNet-master\BiSeNet-master\demo.py", line 60, in main
    model.module.load_state_dict(torch.load(args.checkpoint_path))
  File "C:\Program Files\Python\lib\site-packages\torch\nn\modules\module.py", line 518, in __getattr__
    type(self).__name__, name))
AttributeError: 'BiSeNet' object has no attribute 'module'
PS C:\Users\Administrator\Desktop\BiSeNet-master\BiSeNet-master>
Where do I put the dataset ?

**Comment by hubutui** [comment]
Is your gpu available? If without gpu, you need to map device to cpu when loading pretrained model.

**Comment by EchoAmor** [comment]
Have anyone solved this problem？？？

**Comment by zz10001** [comment]
> Have anyone solved this problem？？？

have you sovled it?

**Comment by zz10001** [comment]
> have you sovled it?

maybe you just delete .module if you just you use one gpu.

**Comment by EchoAmor** [comment]
no I didn't . Thanks I'll try @zz10001

**Comment by Leeyed** [comment]
if your pc have more than one gpu.
Before:
        model.to(device)
You should add: 
        model = nn.DataParallel(model)

BEFORE:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model.to(device)
AFTER:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
if torch.cuda.device_count() > 1:
\Space model = nn.DataParallel(model)
model.to(device)
