### ISSUE TITLE
pixel accuracy calculation algorithm is Wrong!

### ISSUE THREAD

**Issue by FENGShuanglang** [ooooverflow/BiSeNet#13]
pred and label both are 3 channel,so why do you directly flatten() them?

**Comment by ooooverflow** [comment]
Yes, you are right. Thanks for reminding. Just put the `compute_global_accuracy` before transforming one-hot array to RBG array would be all right

**Comment by REFunction** [comment]
> Yes, you are right. Thanks for reminding. Just put the `compute_global_accuracy` before transforming one-hot array to RBG array would be all right

Have you already update this code about the problem

**Comment by ooooverflow** [comment]
@REFunction 
Hi, I have already update the new calculation code of pixel acc
